### ISSUE TITLE
List of attributes

### ISSUE THREAD

**Issue by JensWinter** [MOOChub/schema#3]
Hi there!

Is there a list and description of available course attributes out there? There is an example response object but unfortunately not explanation of the meaning of individual attributes. E.g. "workload", "access", "duration" etc.

Also how can course costs be specified using the MoocHub API?

Thanks in advance!

**Comment by MaxThomasHPI** [comment]
Hello,
there is a more detailed documentation of the separate attributes here:
https://openhpi.stoplight.io/docs/bridges/24529384d7a46-course

for course costs you would use the "offers" attribute (that is the intended usage).

If you still have further questions or this is still not what you are looking for do not hesitate to ask!

cheers!

**Comment by JensWinter** [comment]
Thank you very much. This was very helpful!
